package panels;

/**
 *
 * @author Matheus
 */
public class NotesBlock extends javax.swing.JPanel {

    /**
     * Creates new form NotesBLoc
     */
    public NotesBlock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notesBlockReminderDate = new javax.swing.JLabel();
        notesBlockTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteBlockDescription = new javax.swing.JTextArea();
        notesBlockPriority = new javax.swing.JLabel();
        notesBlockDateCreated = new javax.swing.JLabel();

        notesBlockReminderDate.setText("jLabel1");

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        notesBlockTitle.setEditable(false);
        notesBlockTitle.setText("Título");
        notesBlockTitle.setBorder(null);
        notesBlockTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesBlockTitleActionPerformed(evt);
            }
        });

        noteBlockDescription.setEditable(false);
        noteBlockDescription.setColumns(20);
        noteBlockDescription.setRows(5);
        jScrollPane1.setViewportView(noteBlockDescription);

        notesBlockPriority.setBackground(new java.awt.Color(255, 255, 255));
        notesBlockPriority.setText("Prioridade");
        notesBlockPriority.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        notesBlockDateCreated.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notesBlockTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notesBlockPriority)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notesBlockDateCreated))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notesBlockTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notesBlockPriority))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesBlockDateCreated)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notesBlockTitleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_notesBlockTitleActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_notesBlockTitleActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea noteBlockDescription;
    public javax.swing.JLabel notesBlockDateCreated;
    public javax.swing.JLabel notesBlockPriority;
    public javax.swing.JLabel notesBlockReminderDate;
    public javax.swing.JTextField notesBlockTitle;
    // End of variables declaration//GEN-END:variables
}
