package panels;

import java.awt.event.MouseEvent;
import main.Home;
import pages.EditNotes;
import java.awt.Component;

/**
 *
 * @author Matheus
 */
public class NotesBlock extends javax.swing.JPanel {
    Home home;
    EditNotes editNotes = new EditNotes();

    public NotesBlock(Home home) {
        this.home = home;
        initComponents();
    }

    public void myInitComponents() {
    }

    private void showPopUp(MouseEvent e) {
        popupMenu.show(btnEditNote, e.getX(), e.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notesBlockId = new javax.swing.JLabel();
        popupMenu = new javax.swing.JPopupMenu();
        editOption = new javax.swing.JMenuItem();
        deleteOption = new javax.swing.JMenuItem();
        notesBlockTitle = new javax.swing.JTextField();
        noteBlockDescription = new javax.swing.JTextArea();
        notesBlockReminderDateLabel = new javax.swing.JLabel();
        notesBlockPriority = new javax.swing.JLabel();
        btnEditNote = new javax.swing.JButton();

        notesBlockId.setText("Id");
        notesBlockId.setOpaque(true);

        editOption.setText("Editar");
        editOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOptionActionPerformed(evt);
            }
        });
        popupMenu.add(editOption);

        deleteOption.setText("Deletar");
        deleteOption.setToolTipText("");
        deleteOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOptionActionPerformed(evt);
            }
        });
        popupMenu.add(deleteOption);

        notesBlockTitle.setEditable(false);
        notesBlockTitle.setText("Título");
        notesBlockTitle.setBorder(null);

        noteBlockDescription.setEditable(false);
        noteBlockDescription.setColumns(5);
        noteBlockDescription.setRows(5);
        noteBlockDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        noteBlockDescription.setEnabled(false);

        notesBlockReminderDateLabel.setText("Data do lembrete");

        notesBlockPriority.setBackground(new java.awt.Color(255, 255, 255));
        notesBlockPriority.setText("Prioridade");

        btnEditNote.setText("⋮");
        btnEditNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditNoteMousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditNoteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(notesBlockPriority))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(notesBlockReminderDateLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79,
                                                        Short.MAX_VALUE)
                                                .addComponent(btnEditNote, javax.swing.GroupLayout.PREFERRED_SIZE, 18,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(notesBlockTitle,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(noteBlockDescription,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 195,
                                                                Short.MAX_VALUE))
                                                .addGap(2, 2, 2)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(notesBlockTitle, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(notesBlockPriority))
                                .addGap(8, 8, 8)
                                .addComponent(noteBlockDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(notesBlockReminderDateLabel)
                                        .addComponent(btnEditNote, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                                Short.MAX_VALUE))));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteOptionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteOptionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deleteOptionActionPerformed

    private void editOptionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editOptionActionPerformed
        // id = this.getId();
        // int index = home.tabs.indexOfTab("Editar Nota");
        // home.tabs.setSelectedIndex(index);

    }// GEN-LAST:event_editOptionActionPerformed

    private void btnEditNoteMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEditNoteMousePressed
        showPopUp(evt);
    }// GEN-LAST:event_btnEditNoteMousePressed

    private void btnEditNoteMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEditNoteMouseReleased
        showPopUp(evt);
    }// GEN-LAST:event_btnEditNoteMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditNote;
    private javax.swing.JMenuItem deleteOption;
    private javax.swing.JMenuItem editOption;
    public javax.swing.JTextArea noteBlockDescription;
    public javax.swing.JLabel notesBlockId;
    public javax.swing.JLabel notesBlockPriority;
    public javax.swing.JLabel notesBlockReminderDateLabel;
    public javax.swing.JTextField notesBlockTitle;
    public javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
