package pages;

import classes.*;

/**
 *
 * @author Matheus
 */
public class EditNotes extends javax.swing.JPanel {

        NewNote newNote = new NewNote();
        SqlDateFormatter sdf = new SqlDateFormatter();

        /**
         * Creates new form editNotes
         */
        public EditNotes() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                noteId = new javax.swing.JLabel();

                noteId.setText("jLabel2");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 726, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 388, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveNoteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveNoteActionPerformed
                // try {
                // DBController db = new DBController("notes.db");
                // int id = Integer.parseInt(noteId.getText());
                // String title = noteTitle.getText();
                // String description = noteDescription.getText();
                // String priority = (String) notePriority.getSelectedItem();
                // Date reminderDate = new java.sql.Date(noteReminderDate.getDate().getTime());
                //
                // db.updateNotes(id, title, description, priority, reminderDate);
                // JOptionPane.showMessageDialog(null, "Nota atualizada com sucesso!");
                // } catch (Exception e) {
                // JOptionPane.showMessageDialog(null, e.getMessage());
                // }
        }// GEN-LAST:event_btnSaveNoteActionPerformed

        private void noteTitleMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newNoteTitleMousePressed
                // TODO add your handling code here:
        }// GEN-LAST:event_newNoteTitleMousePressed

        private void noteTitleKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_newNoteTitleKeyPressed
                // TODO add your handling code here:
        }// GEN-LAST:event_newNoteTitleKeyPressed

        private void noteDescriptionKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_newNoteDescriptionKeyPressed
                // TODO add your handling code here:
        }// GEN-LAST:event_newNoteDescriptionKeyPressed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JLabel noteId;
        // End of variables declaration//GEN-END:variables
}
