package pages;

import classes.*;

/**
 *
 * @author Matheus
 */
public class EditNotes extends javax.swing.JPanel {

    NewNote newNote = new NewNote();
    SqlDateFormatter sdf = new SqlDateFormatter();

    /**
     * Creates new form editNotes
     */
    public EditNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noteId = new javax.swing.JLabel();
        noteTitle = new javax.swing.JTextField();
        notePriority = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteDescription = new javax.swing.JTextPane();
        noteReminderDate = new com.toedter.calendar.JDateChooser();
        dateCreatedLabel = new javax.swing.JLabel();
        btnSaveNote = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        noteId.setText("jLabel2");

        noteTitle.setText("Título");
        noteTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noteTitleMousePressed(evt);
            }
        });
        noteTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noteTitleKeyPressed(evt);
            }
        });

        notePriority.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Prioridade", "Urgente", "Alta", "Média", "Baixa", "Opcional", "Trivial" }));
        notePriority.setToolTipText("Prioridade");
        notePriority.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        noteDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noteDescription.setText("Descrição");
        noteDescription.setCaretPosition(0);
        noteDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noteDescriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(noteDescription);

        noteReminderDate.setDateFormatString("d/MM/y");

        dateCreatedLabel.setText("Data: " + sdf.formatSqlDate(newNote.getDateCreated()));

        btnSaveNote.setText("jButton1");
        btnSaveNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNoteActionPerformed(evt);
            }
        });

        jLabel1.setText("Lembrar-me");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(dateCreatedLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(noteTitle)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 214,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(notePriority,
                                                                javax.swing.GroupLayout.Alignment.TRAILING, 0, 94,
                                                                Short.MAX_VALUE)
                                                        .addComponent(noteReminderDate,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jLabel1,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnSaveNote,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(noteTitle, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(notePriority, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(3, 3, 3)
                                                .addComponent(noteReminderDate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSaveNote))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateCreatedLabel)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveNoteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveNoteActionPerformed
        // try {
        // DBController db = new DBController("notes.db");
        // int id = Integer.parseInt(noteId.getText());
        // String title = noteTitle.getText();
        // String description = noteDescription.getText();
        // String priority = (String) notePriority.getSelectedItem();
        // Date reminderDate = new java.sql.Date(noteReminderDate.getDate().getTime());
        //
        // db.updateNotes(id, title, description, priority, reminderDate);
        // JOptionPane.showMessageDialog(null, "Nota atualizada com sucesso!");
        // } catch (Exception e) {
        // JOptionPane.showMessageDialog(null, e.getMessage());
        // }
    }// GEN-LAST:event_btnSaveNoteActionPerformed

    private void noteTitleMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newNoteTitleMousePressed
        // TODO add your handling code here:
    }// GEN-LAST:event_newNoteTitleMousePressed

    private void noteTitleKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_newNoteTitleKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_newNoteTitleKeyPressed

    private void noteDescriptionKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_newNoteDescriptionKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_newNoteDescriptionKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveNote;
    private javax.swing.JLabel dateCreatedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane noteDescription;
    public javax.swing.JLabel noteId;
    private javax.swing.JComboBox<String> notePriority;
    private com.toedter.calendar.JDateChooser noteReminderDate;
    private javax.swing.JTextField noteTitle;
    // End of variables declaration//GEN-END:variables
}
