package pages;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.text.DefaultCaret;

public class Notes extends javax.swing.JPanel {

    public Notes() {
        initComponents();
        myInitComponents();
    }

    public void myInitComponents() {

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                searchNotes.requestFocusInWindow();
            }
        });

        // searchNotes.addActionListener(new ActionListener() {;
        // @Override
        // public void actionPerformed(ActionEvent e) {
        // performSearch();
        // }
        // });
    }

    // public void performSearch() {
    // String searchText = searchNotes.getText();
    // // code to perform search using searchText
    // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notesPanel = new javax.swing.JPanel();
        searchNotes = new javax.swing.JTextField();

        notesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Notas"));
        notesPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout notesPanelLayout = new javax.swing.GroupLayout(notesPanel);
        notesPanel.setLayout(notesPanelLayout);
        notesPanelLayout.setHorizontalGroup(
                notesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        notesPanelLayout.setVerticalGroup(
                notesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 169, Short.MAX_VALUE));

        searchNotes.setText("Pesquisar notas");
        searchNotes.setCaretPosition(0);
        searchNotes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchNotesFocusGained(evt);
            }
        });
        searchNotes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchNotesKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 298,
                                                Short.MAX_VALUE)
                                        .addComponent(notesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 298,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchNotes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124,
                                        Short.MAX_VALUE)
                                .addComponent(notesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void searchNotesKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_searchNotesKeyPressed
        if (searchNotes.getText().equals("Pesquisar notas")) {
            searchNotes.setText("");
        }
        searchNotes.setForeground(Color.BLACK);
    }// GEN-LAST:event_searchNotesKeyPressed

    private void searchNotesFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_searchNotesFocusGained
        searchNotes.requestFocusInWindow();
        if (searchNotes.getText().equals("Pesquisar notas")) {
            searchNotes.setForeground(Color.LIGHT_GRAY);
        } else {
            searchNotes.setForeground(Color.BLACK);
        }

    }// GEN-LAST:event_searchNotesFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notesPanel;
    public javax.swing.JTextField searchNotes;
    // End of variables declaration//GEN-END:variables
}
