package main;

import java.awt.*;

public class Home extends javax.swing.JFrame {

    CardLayout cardLayout = new CardLayout();

    public Home() {
        initComponents();
        contentPanel.setLayout(cardLayout);
        contentPanel.add(newNote, "NewNote");
        contentPanel.add(newTaskList, "NewTaskList");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPanel = new javax.swing.JSplitPane();
        sideMenuPanel = new javax.swing.JPanel();
        btnNewNote = new javax.swing.JButton();
        btnNewTaskList = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        newTaskList = new pages.Reminders();
        newNote = new pages.Notes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPanel.setDividerLocation(130);
        jSplitPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        sideMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sideMenuPanel.setAlignmentX(0.0F);
        sideMenuPanel.setAlignmentY(0.0F);
        sideMenuPanel.setPreferredSize(new java.awt.Dimension(80, 80));

        btnNewNote.setText("Notas");
        btnNewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNoteActionPerformed(evt);
            }
        });

        btnNewTaskList.setText("Lista de Tarefas");
        btnNewTaskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTaskListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuPanelLayout = new javax.swing.GroupLayout(sideMenuPanel);
        sideMenuPanel.setLayout(sideMenuPanelLayout);
        sideMenuPanelLayout.setHorizontalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNewNote)
                    .addComponent(btnNewTaskList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideMenuPanelLayout.setVerticalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewNote, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewTaskList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPanel.setLeftComponent(sideMenuPanel);

        contentPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(newTaskList, "card3");
        contentPanel.add(newNote, "card2");

        jSplitPanel.setRightComponent(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewTaskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTaskListActionPerformed
        cardLayout.show(contentPanel, "NewTaskList");
    }//GEN-LAST:event_btnNewTaskListActionPerformed

    private void btnNewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNoteActionPerformed
        cardLayout.show(contentPanel, "NewNote");
    }//GEN-LAST:event_btnNewNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewNote;
    private javax.swing.JButton btnNewTaskList;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JSplitPane jSplitPanel;
    private pages.Notes newNote;
    private pages.Reminders newTaskList;
    private javax.swing.JPanel sideMenuPanel;
    // End of variables declaration//GEN-END:variables
}